#插件版本识别，请勿修改
Version: 1.0.2

Settings:
    Punch:
        #打孔成功率（熔炉烧造）
        Chance: 20
    Drop:
        #宝石掉落率（挖掉钻石原矿掉出宝石的几率）
        Chance: 20
    DIAMOND:
        #宝石等级差别化倍率，表示每一级宝石的掉率是上一级宝石的x倍
        #如设为6，表示理论上挖7个宝石，有6个1级，1个2级，挖43个宝石，则36个1级，6个2级，1个3级
        Multiple: 6
        Level:
            #每一级钻石增加的伤害数值
            Damage:
                1: 1.0
                2: 2.0
                3: 3.0
                4: 4.0
                5: 5.0
                6: 6.0
                7: 7.0
                8: 8.0
                9: 9.0
                10: 10.0